// DSL components — all are "use client" and safe to pass through MDX component map
export { default as Scene } from "./Scene.client"
export { default as Model } from "./Model.client"
export { default as Group } from "./Group.client"
export { default as Lighting } from "./Lighting.client"
export { default as CanvasConfig } from "./CanvasConfig.client"
export { default as ScrollTrack } from "./ScrollTrack.client"
export { default as Keyframe } from "./Keyframe"
export { default as CameraRig } from "./CameraRig.client"
export { default as LayoutStep } from "./LayoutStep.client"
export { default as Prose } from "./Prose.client"
export { default as Hotspot } from "./Hotspot.client"
export { default as Label } from "./Label.client"
export { default as Annotation } from "./Annotation.client"
export { default as GridStage } from "./GridStage.client"
export { default as GridState } from "./GridState"
export { default as Cell } from "./Cell.client"
export { default as GridSequence } from "./GridSequence.client"

export { SceneRegistryProvider } from "./SceneRegistry"
export { SceneObjectRegistryProvider } from "./SceneObjectRegistry"
export { useScrollProgress } from "./useScrollProgress"
